### ISSUE TITLE
sSYN should be non-transferable

### ISSUE THREAD

**Issue by aureliusbtc** [synapsecns/synapse-contracts#110]
#45 - sSYN is currently transferable, this is undesired behavior. sSYN should be non-transferable, and have a test case around this.

**Comment by ChiTimesChi** [comment]
@aureliusbtc why sSYN being transferable is undesired behavior? sAVAX is transferable, and has very similar mechanics:

https://staking.benqi.fi/stake
https://snowtrace.io/token/0x2b2c81e08f1af8835a78bb2a90ae924ace0ea4be

The current implementation allows to transfer only the "delegaled" SYN, which are in fact fungible tokens. "Undelegated" sSYN are burnt at the undelegation request, so they can't be transferred.
https://github.com/synapsecns/synapse-contracts/blob/31794b4427b051f5de3690715f77740496c8b4e2/contracts/staking/StakedSYN.sol#L102

If this was to be deployed on less expensive chain than Mainnet, one could argue for minting a transferable NFT representing "unlocking" SYN after the undelegate request for maximum capital efficiency.

**Comment by aureliusbtc** [comment]
Closing in favor of keeping it transferrable
